### ISSUE TITLE
Request for Inclusion of an API Implementation

### ISSUE THREAD

**Issue by jsievertde** [openl2m/openl2m#5]
Hi,

we really like your project and would like to use it internally for our own network.
For that we would like to implement an API for request to openl2m for information or to change some settings.
If we implement the api app with all urls ourselves would you be interested in us providing this as part of your project ?

Thanks for your work on this.

**Comment by jsievertde** [comment]
And additionally would you prefer it if the implementation would be in it's own app or as part of the `switches` app for a faster inclusion in your code base.

**Comment by johanreinalda** [comment]
I would be very open to this. This has been a long term goal to implement, but i have not had time for this yet.
I would prefer this inside the switches app, and use the standard django rest framework from https://www.django-rest-framework.org/

**Comment by jsievertde** [comment]
Hi,
I already did some very basic POC work for API-Endpoints that we need.
Right now for us the read-only endpoints are a priority.
If you want you can look at some of the changes and tell me if you would like some changes before I spent to much time on a path that conflicts with your vision.
https://git.schunternet.de/snet/openl2m/src/branch/api/read-only

**Comment by jsievertde** [comment]
@johanreinalda 
You removed the manuf static file from the main branch.
Will you properly replace it with an update query so that it will be deployed at the beginning if it is not there yet or what are your plans with that.

**Comment by johanreinalda** [comment]
i will try to take a look at your code in the coming days (this is not part of my full-time job :-). )
With regard to the manuf code, if you run update.sh after upgrades, that should pull in the latest database file.

**Comment by johanreinalda** [comment]
taking a quick cursory look at the work:
in general, OK with it, but I would like the API entry point to start at /api, with additional entries into the various apps that may in the future support it. E.g /api/switches/search, /api/switches/activity etc. This gives us more flexibility down the road to extend.
I apologize if I wasn't clear in my previous message. Take a look at netbox at https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/urls.py how they have implemented that by handing off the top level api entry point into various apps. In the openl2m case, we would initial (maybe ever) only have /api/switches

Thoughts?

**Comment by jsievertde** [comment]
Hmm,
this looks much nicer from the structure. I will then simply copy that from netbox but it is only some code that I have to move around.

Nah mostly I try to always fully separate apps in Django if they have different entry points, but that is only a personal preference for me but the netbox way will also properly separate the api code from the normal views.

How do you feel about the use of black as an automatic code styler  ?
I already used it for `switches/url.py` and `switches/views.py ` but I can undo that if your prefer a different style for your code.

**Comment by johanreinalda** [comment]
i am fine with using black. Been using it internally for other projects, never got around to migrating this... So, I just did. I pushed by development branch, updated with black. No other changes (other then docs updates). I will push that to the main branch after some more testing.

**Comment by johanreinalda** [comment]
merge your code into a dev branch, and started testing it. In general it works fine. 
Couple of observations:
APISwitchDetailView() returns all attributes that are part of the other calls (arp, speed, etc.) including the interface-specific calls. So not sure why the others are needed?

Same with APIInterfaceDetailView(), returns all attributes for that interface that are in the 'smaller' requests (arp, speed, etc), so not why the others are needed.

I could buy off on the APIInterfaceDetailView() but even that is a duplicate.

Additionally, interface name is not returned (i added it), and only a single mac address is returned, instead of the list of found. I fixed that.

Finally, the vlan returned is the untagged, and there is no list of vlans for a tagged interfaces. I will fix that as well.

Finally, I will move this to /api/switches/ as well.

Thoughts, comments ?

**Comment by jsievertde** [comment]
Hey
sorry was on vacation until this week so no further work on this from my side.
The single views are for later when I wanted to explicitly query only the needed information from the underlying devices.
This would reduce the answer time for all of the less detail oriented API endpoints.

Right now we have a 1,5 second to first collect all information from a switch and then parse the dictionary to only extract the needed information for the interface.
At least for our use case we then have to implement async JavaScript based update of the dom to not have to wait to long for the needed information.

My question would be if you even want to be able to only request certain information from a switch or an interface.
Let me know if you think that  would make it to complicated.
Most likely I will only be able to start working on this again on Monday anyway.

**Comment by johanreinalda** [comment]
I did some work on this today. I think that
-there should be a single 'switch details' call. Since this already has to run the full switch config, it makes no sense to have the individual "get interface xyz" call, since they also have to run the full config.
-there should be individual calls for interface set_state,set_vlan,set_poe,set_description.

I've updated the api code and moved it to /api/ etc. I added a as_dict() function to all relavant classes, to format data needed for the api. This simplifies the api view. I added ethernet, arp and lldp as part of the interface data. Still have to add PoE, running out of time today.

Still work to be done with the api browsing, and the POST/set modules need to flushed out...but take a look at the "api-read-only" branch for the current state...

**Comment by johanreinalda** [comment]
Will also need to look at the drf caching, since the current caching is http-request-session based, and does not work in rest. So all “interface only” calls will call the full get-details() regardless of just requesting a single interface. Caching after first call me help that. Additionally, permission checks need work. Note I will be traveling next week mon-wed so no time…

**Comment by johanreinalda** [comment]
Just pushed a flushed out "write" implementation. This has been tested very lightly on a single device. This needs a lot of work on permissions testing, and logging needs to be added. Also, this allows for a lot of refactoring duplicate code between switches/views.py and switches/api/views.py; however, that is a large amount of work that may be better done at a later stage...
Note this is my first Django REST implementation, so lots of room for improvements :-)

**Comment by jsievertde** [comment]
Sorry for my long silence but my bandwidth has just been a little low the last weeks.
I just read through your code and it looks easier to maintain than the version i cobbled together for testing.

I will test it on some of our reliable and never changing devices where I can just redeploy the config file after some testing.
Otherwise I will try to actually help you instead of just asking you to put more work in yourself.

Thanks for your work. I appreciate it.

**Comment by johanreinalda** [comment]
i pushed a lot of changes, the API is now mostly browsable. Enjoying learing this rest framework. Will start work on refactoring/collapsing the Web UI and REST calls in the near future; that should solve the permissions also.

**Comment by johanreinalda** [comment]
let me know (if you can) what devices you test with, and I will add that to the docs.

**Comment by jsievertde** [comment]
> let me know (if you can) what devices you test with, and I will add that to the docs.
I have right now only direct access to the following devices:
HPE J4905A (3400CL-24G)
HP JD374A (5500 24G-SFP)
HPE J9021A (2810 24G)
HPE J9776A (2530 24G)
HPE J9775A (2530 48G)

Those are all older but the only ones were I can independently test everything.

**Comment by johanreinalda** [comment]
latest commit has most refactoring complete. actions.py now implements the actual performing of changes, called by both Web UI and API functions. Also included is some basic API documentation...

**Comment by johanreinalda** [comment]
current push has token interface for users (see top-right menu), and implements token expiration date, and token read-only permission checks.

**Comment by johanreinalda** [comment]
Just push v3.0 to the development branch. This will be the original release of the REST API after some more testing. Note that the get-token-over-api has been moved to /api/users/token/ ...

**Comment by johanreinalda** [comment]
I will be closing this ticket. The development branch has the functioning REST api with docs. I will move this to "main" in early 2024 for the v3.0.x release.
